### ISSUE TITLE
Better error message in ErrorBoundary for lazy-loaded routes.

### ISSUE THREAD

**Issue by paddycy** [avantgardefinance/melon-terminal#375]
I clicked on create a fund and got this error in the image.

I refreshed and it was fine.

![image](https://user-images.githubusercontent.com/29010197/74910663-b6462580-53c3-11ea-9e37-dd1b212331ae.png)

**Comment by iherger** [comment]
This usually happens when a new version of the Melon Terminal was deployed while you still have the old version loaded in the browser.

Can you try to reload the page completely, and then start again?

**Comment by fubhy** [comment]
Yes, this is an expected error in the explained scenario. We should, however, make the ErrorBoundary for these lazy loaded components reflect that (simply state that a reload fixes the problem).

We can't prevent this error from happening on now.sh due to the nature of the deployments. So whenever a new release is deployed under your feet the references to the .js files are no longer valid. Hence this error.

Thanks for bringing it up! I'll rename the issue title accordingly.
