### ISSUE TITLE
Error in transaction "Take order on Kyber"

### ISSUE THREAD

**Issue by carumusan** [avantgardefinance/melon-terminal#444]
gas required exceeds allowance (9948504) or always failing transaction

**Comment by fubhy** [comment]
Thanks for reporting.

There are currently two reasons (that we know of) for a failing transaction on Kyber:

1. The policies associated with your fund disallow the transaction. We currently do not fully validate this on the frontend yet (there is an open pull request that aims to fix this: https://github.com/avantgardefinance/melon-terminal/pull/432). This will be fixed within the coming week.

2. The offered rates from Kyber changed between querying the rates and executing the transaction. This happens if the Kyber reserve with the best rate for your request sent a rate update in a block right before your transaction or exactly in the same block. There is sadly nothing we can do about this except showing a better error message (we are also working on this).

Did you try closing the transaction modal and executing the trade a second time?

**Comment by carumusan** [comment]
I managed to make the trade after refreshing trying again.
