### ISSUE TITLE
Error in transaction "Cancel investment request"

### ISSUE THREAD

**Issue by lulepu** [avantgardefinance/melon-terminal#446]
Error: Timeout exceeded during the transaction confirmation process. Be aware the transaction could still get confirmed!
    at https://melon.avantgarde.finance/static/js/6.8205447f.chunk.js:2:1019834
    at c (https://melon.avantgarde.finance/static/js/6.8205447f.chunk.js:2:1622505)
    at Generator._invoke (https://melon.avantgarde.finance/static/js/6.8205447f.chunk.js:2:1622258)
    at Generator.forEach.e.<computed> [as next] (https://melon.avantgarde.finance/static/js/6.8205447f.chunk.js:2:1622862)
    at r (https://melon.avantgarde.finance/static/js/6.8205447f.chunk.js:2:1068005)
    at s (https://melon.avantgarde.finance/static/js/6.8205447f.chunk.js:2:1068216)

**Comment by lulepu** [comment]
I get this error, when trying to "cancel investment request". it also hasnt been working, when trying to make the investment, even i was in the time window.

**Comment by lulepu** [comment]
why do i even has to cancel it, when the window already closed. is there a was, that it cancels itself? Also is there a possibility to make timed transactions, so that you can make a investment plus the execution in one session somehow?

**Comment by iherger** [comment]
@lulepu, thanks for reporting this. 

Can you tell us the name of the fund or the address of the fund, so that we can have a closer look?

**Comment by lulepu** [comment]
Tried to invest in "carneval".

**Comment by iherger** [comment]
Unfortunately, I can't see anything in the contract logs/events on why this happened. Failed investment transactions with this fund should be visible in https://etherscan.io/address/0x54c1761256d838159948169e3a665c88c62da937

I manually cancelled the one expired investment request for the fund `Carneval`, so you should have the assets back in your wallet.

BTW: I just saw that this investor address has a number of expired investment requests for very old funds. In order to move the requested investment assets back to the wallet, you should cancel also those old investment request. You should be able to see them in your wallet page, https://melon.avantgarde.finance/wallet

**Comment by fubhy** [comment]
@lulepu Hey there. One more thing to note is that timeout errors during a transaction are caused by a too low gas price. If you run into such a case and your transaction remains in pending state (you can e.g. check the state on Etherscan), try cancelling your transaction (for instance in Metamask) and try again with higher gas price. 

A timeout is not exactly an "error" in the common sense in this case because the transaction could still get confirmed (as stated in the error message) but it could also have a much too low gas price causing it to never get confirmed. So instead of continuing to watch the transaction state infinitely we decided to add a timeout for now. There is already a follow-up issue that will remove the timeout again and implement a better solution (notifying the user in a more user friendly way and allowing the to conveniently cancel the transaction from the browser: https://github.com/avantgardefinance/melon-terminal/issues/400).

**Comment by lulepu** [comment]
Hey thanks, 

 

i cant cancel requests, because “gas required exceeds allowance (10000000) or always failing transaction”

 

can you help me with that too please?

 

Von: Ivan Herger <notifications@github.com>
Antworten an: avantgardefinance/melon-terminal <reply@reply.github.com>
Datum: Montag, 2. März 2020 um 21:27
An: avantgardefinance/melon-terminal <melon-terminal@noreply.github.com>
Cc: lulepu <lulepu@posteo.de>, Mention <mention@noreply.github.com>
Betreff: Re: [avantgardefinance/melon-terminal] Error in transaction "Cancel investment request" (#446)

 

Unfortunately, I can't see anything in the contract logs/events on why this happened. Failed investment transactions with this fund should be visible in https://etherscan.io/address/0x54c1761256d838159948169e3a665c88c62da937

I manually cancelled the one expired investment request for the fund Carneval, so you should have the assets back in your wallet.

BTW: I just saw that this investor address has a number of expired investment requests for very old funds. In order to move the requested investment assets back to the wallet, you should cancel also those old investment request. You should be able to see them in your wallet page, https://melon.avantgarde.finance/wallet

**Comment by iherger** [comment]
There seems to be a bug here. We are looking into it.

BTW: for funds that were created with the old protocol versions, it is not possible to cancel expired requests by other users (this was introduced with the new protocol version), so we cannot cancel the request for you.
