### ISSUE TITLE
Error in transaction "Invest"

### ISSUE THREAD

**Issue by jiamijiang** [avantgardefinance/melon-terminal#457]
Parameter|Value
------|-----
Contract|[0x65a89272AFA06aff279f626bd974b358B3fb5Fd0](https://etherscan.io/address/0x65a89272AFA06aff279f626bd974b358B3fb5Fd0)
Method|requestInvestment
Arguments|["1000000000000000000","1000000000000000000","0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"]
Sender|[0x8f4c07878e9bb0c61baaefaa18738ead78005286](https://etherscan.io/address/0x8f4c07878e9bb0c61baaefaa18738ead78005286)

Stack trace: Error: Node error: {"code":-32000,"message":"gas required exceeds allowance (9896693) or always failing transaction"}
    at Function.value (https://melon.avantgarde.finance/static/js/6.e98349f5.chunk.js:2:726356)
    at e.<anonymous> (https://melon.avantgarde.finance/static/js/6.e98349f5.chunk.js:2:747609)
    at c (https://melon.avantgarde.finance/static/js/6.e98349f5.chunk.js:2:7198448)
    at Generator._invoke (https://melon.avantgarde.finance/static/js/6.e98349f5.chunk.js:2:7198201)
    at Generator.forEach.e.<computed> [as next] (https://melon.avantgarde.finance/static/js/6.e98349f5.chunk.js:2:7198805)
    at r (https://melon.avantgarde.finance/static/js/6.e98349f5.chunk.js:2:1070022)
    at s (https://melon.avantgarde.finance/static/js/6.e98349f5.chunk.js:2:1070233)

**Comment by iherger** [comment]
Hi

Thanks for reporting this.

There are a few issues that I can see:
- the amount of WETH that the address 0x8f4c07878e9bb0c61baaefaa18738ead78005286 ows is lower than the amount to be invested (the address owns no WETH at all, and wants to invest 1 WETH). This should have been shown as an error by the Melon Terminal. We will try to fix this in the Melon Terminal.
- there is only 0.01 ETH in the wallet. However, to do this transaction, you need more, namely 0.01 ETH as the incentive payment and some amount for gas usage. 

So in order to get this working, you should have 1 WETH in your wallet (for investing into the fund) as well as about 0.1 ETH (to pay incentive and gas costs).

Can you try if this works for you?

**Comment by jiamijiang** [comment]
I converted slightly more than 1 ETH to slightly more than 1 WETH already.
I do realize it is not in my Dapper wallet but I do see it under 'Account
Balances'

[image: image.png]

the next question is, how do i use this amount of WETH that i have?

**Comment by iherger** [comment]
We have now prepared a special deployment which should help us for debugging your error: https://melon-terminal-git-debug-invest-transaction.avantgarde-finance.now.sh

Can you try your transaction again, and report back once you have done this? Thanks a lot!

It should automatically start the `requestInvestment` transaction (please check the suggested gas price, and maybe adapt it in Metamask or any other connection you are using).

**Comment by iherger** [comment]
This issue was caused by too little ETH in the account (only 0.01 ETH, but `requestInvestment` requires a bit more, namely 0.01 ETH for the incentive, about 0.004 ETH for amgu, and some ETH for gas).
