### ISSUE TITLE
Error in transaction "Invest"

### ISSUE THREAD

**Issue by jeanmatthieu58** [avantgardefinance/melon-terminal#460]
Hi,new here and new in crypto,i have a problem with my fund on melons have this node error gas is missing but I don't understand why, I have WETH and ETH in my wallet.does someone can help me 

Parameter|Value
------|-----
Contract|[0x9fedE1B116Ae1b2a58113Edb4E0C2886381798B3](https://etherscan.io/address/0x9fedE1B116Ae1b2a58113Edb4E0C2886381798B3)
Method|requestInvestment
Arguments|["470000000000000000","470000000000000000","0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"]
Sender|[0x4CF1FC305Dfb17E01fD47A16e65BdC980F7e451D](https://etherscan.io/address/0x4CF1FC305Dfb17E01fD47A16e65BdC980F7e451D)

Stack trace: value@https://melon.avantgarde.finance/static/js/6.e98349f5.chunk.js:2:726365
https://melon.avantgarde.finance/static/js/6.e98349f5.chunk.js:2:747617
c@https://melon.avantgarde.finance/static/js/6.e98349f5.chunk.js:2:7198452
https://melon.avantgarde.finance/static/js/6.e98349f5.chunk.js:2:7198202
r@https://melon.avantgarde.finance/static/js/6.e98349f5.chunk.js:2:1070022
s@https://melon.avantgarde.finance/static/js/6.e98349f5.chunk.js:2:1070234
promiseReactionJob@[native code]

**Comment by iherger** [comment]
Hi

Thanks a lot for reporting this error.

You seem to have enough WETH and ETH in you wallet, indeed, so that should work in principle.

It would be great, if you could help us debug the problem. For this, we will prepare a special deployment of the Melon Terminal which should give you and use more details on why the transaction is failing. 

I will post the address of the special deployment here. If possible, you can also send me your Telegram handle to ivan@avantgarde.finance.

**Comment by iherger** [comment]
OK, so here is a special deployment for debugging: https://melon-terminal-git-debug-invest-transaction.avantgarde-finance.now.sh

Can you try your transaction again, and report back once you have done this? Thanks a lot!

It should automatically start the `requestInvestment` transaction (please check the suggested gas price, and maybe adapt it in Metamask or any other connection you are using).

**Comment by jeanmatthieu58** [comment]
HI  Ivan

I did the transaction again on the debugging deployment and there wasn’t any problem

**Comment by iherger** [comment]
This was an issue with Fortmatic, which they have now solved.
