### ISSUE TITLE
You have a pending investment request: Wait for the execution window to execute your investment request.

### ISSUE THREAD

**Issue by AlexanderBeasant** [avantgardefinance/melon-terminal#469]
Hi,

I deposited 0.6 WETH into my fund yesterday but I get the message as per the subject above.

Please could you confirm the solution?

Thanks,
Alex

**Comment by jennazenk** [comment]
Hello Alexander, 
Investing in a fund that already has outstanding shares is a two step process, to avoid share price manipulation. The first step is making an investment request into the fund (what you just did). The second step has to happen after the next pricefeed update, and before the request expires (request lifetime 24 hours). So that gives an execution window specified in the message you saw. You can come back during that execution window and you will have the option to "Execute" your investment request, which will finalize your investment in the fund. It is also possible that when you come back your request has already been executed by someone else (anyone can execute investment requests, and that is incentivized). 
If the fund had no outstanding shares, you wouldn't need to wait for a pricefeed update and could execute your request right away.

For more on why it is a two step investment process: https://medium.com/melonprotocol/protecting-participants-ee55a752287

**Comment by AlexanderBeasant** [comment]
Thanks for the update Jenny - makes sense!

I was able to follow your process and I've successfully added capital.

Thanks again for your help.
Alex
