### ISSUE TITLE
Fund url: only attribute fund url for funds starting on 1.1 or more recent versions

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/melon-terminal#474]

**Comment by iherger** [comment]
I suggest to keep the fund url for all funds for simplicity, otherwise we have to differentiate between older funds and newer funds both in the Melon Terminal and in the subgraph.

I would then change the subgraph in such a way that older funds automatically have the name of the version appended, e.g. `zahreddino-version-0-9-44` for `ZAHREDDINO` on version 0.9.44, and only funds starting with version 1.1.0 have the short URL.

**Comment by jennazenk** [comment]
Yeah good idea, @fubhy suggested we could put the older versions directly in the subdomain like myfund.v-1-0-5.melon.fund

**Comment by iherger** [comment]
This has been implemented. We are using `my fund-v-1-0-5.melon.fund` for funds on old versions.
