### ISSUE TITLE
Error in transaction "Create Accounting Contract"

### ISSUE THREAD

**Issue by cordycrypto** [avantgardefinance/melon-terminal#479]
Error message: Node error: {"code":-32016,"data":"Reverted","message":"The execution failed due to an exception."}
Fund: Beak 
URL: https://melon.avantgarde.finance/mainnet/fund/0x5408c017EDbb40511D344290F3fC71557AFff849
Contract: [0x5f9AE054C7F0489888B1ea46824b4B9618f8A711](https://etherscan.io/address/0x5f9AE054C7F0489888B1ea46824b4B9618f8A711)
Method: createAccountingFor
Arguments: ["0x13E9cD9E29a2C935C8B9CFdE7eF657f9CaAD9825"]
Sender: [0x13E9cD9E29a2C935C8B9CFdE7eF657f9CaAD9825](https://etherscan.io/address/0x13E9cD9E29a2C935C8B9CFdE7eF657f9CaAD9825)
Connection: fortmatic
Network: MAINNET
Stack trace: value@https://melon.avantgarde.finance/static/js/6.d3e7b83b.chunk.js:2:714782
https://melon.avantgarde.finance/static/js/6.d3e7b83b.chunk.js:2:736034
c@https://melon.avantgarde.finance/static/js/6.d3e7b83b.chunk.js:2:7089822
https://melon.avantgarde.finance/static/js/6.d3e7b83b.chunk.js:2:7089572
r@https://melon.avantgarde.finance/static/js/6.d3e7b83b.chunk.js:2:1048985
s@https://melon.avantgarde.finance/static/js/6.d3e7b83b.chunk.js:2:1049197
promiseReactionJob@[native code]

**Comment by fubhy** [comment]
Hi Cordy!

Thanks for reporting. As discussed on Telegram, this originally sounded very much like the same Fortmatic error we've been seeing over the past 2 weeks. However, Fortmatic actually performed a fix for what seemed to be the problem for that a few days ago and we've since seen much less of this. Also, I checked your sender address and while there is one incident of this particular Fortmatic error in your transaction history, it was 27 days ago (https://etherscan.io/tx/0x376785ac2cadcbb725e1686e6d706f9cf9a8745ef49716c9f5297b8feb0a134e). The transaction (beginSetup) that failed there has since worked for you (see here: https://etherscan.io/tx/0x93de7856e145b129017aafa56b18bd688e5d304db32dbe99ee95e7474756e327)

Sadly, there's nothing I can do in terms of debugging right now because there's no transaction for this error for me to look at. Would you mind trying again and report back here after? For that, please just head to https://melon.avantgarde.finance/mainnet/fund/0x5408c017EDbb40511D344290F3fC71557AFff849 and log in using Fortmatic. It should automatically offer you to continue with the fund setup from there on.

Thanks and sorry for the inconvenience!

**Comment by iherger** [comment]
@cordycrypto , we have also discussed this in the Telegram group on Friday. 

Please to transfer some ETH (0.5 ETH should be enough+) to your account, and continue the setup process, as described by @fubhy. That should work. If not, please feel free to re-open this issue.
