### ISSUE TITLE
Made a mistake a stage 2 of opening melon fund 

### ISSUE THREAD

**Issue by AngoCapital** [avantgardefinance/melon-terminal#536]
Hi, I made a mistake with the performance fees when opening my melon fund, how do i either change the performance fee or start from the beginning?  any help would be very much appreciated.

**Comment by iherger** [comment]
Yes, once the parameters are set, you cannot change them. It's probably best to just abandon the fund at this stage, to save the setup costs.

You will have to use a different wallet address to set up a new fund. If you are using a hardware wallet, you will have many addresses to use.

You cannot use the same name, because a fund name has to be unique.

You probably have to transfer your money in your wallet to your new wallet address.

**Comment by AngoCapital** [comment]
Ok, thank you very much for your help, very fast response.  Thank you.

**Comment by iherger** [comment]
You are welcome. You can also ask questions in our Telegram channel: https://t.me/melonport, which might be easier.
