### ISSUE TITLE
$53 investment, $11 in gas fees smh 

### ISSUE THREAD

**Issue by Category55** [avantgardefinance/melon-terminal#588]
So to invest $53 I had to do it in two transactions?? I pay gas twice to invest once ?? This is the special melon protocol?? This is some scam BS I want a refund of my ether. These fees are hidden fees designed to block the first transactions thus I must redo the invest which means I pay gas 4x now for the single transaction.

Somewhere in etherscan I saw I pay $5 in fees for $3 transaction. I dont know why that is because I clicked a button labeled low gas 75 gwei and thank you very much Melon protocol please refund my ether. I want nothing to do with Melon scam

**Comment by fubhy** [comment]
Hi. In the midst of your rambling you must've forgotten to provide the necessary details about your fund and the relevant addresses for me to be able to look into it and maybe provide some help.

In general, gas fees are really high right now on Ethereum. Hence, naturally transactions are going to be more expensive than usual. We are working on improving this within our capabilities for the Melon Protocol (as this is a Network-wide problem) by investigating Layer 2 Solutions as well as improving our Contracts efficiency.

Investment is a two step process. The first is two ERC20.approve and the second is the actual investment. All of this is also described in much detail on https://melonprotocol.com - There is also a youtube video recording that also features this two step investment process and fund setup in general.

I am going to close your issues due to the tone. If you want assistance from our development team please file a new issue in a friendly and professional tone and we are more than happy to help you out.

**Comment by Category55** [comment]
i sincerely apologize for the tone
