### ISSUE TITLE
Invested Ether - Redeem Chainlink ??? I need help here

### ISSUE THREAD

**Issue by Category55** [avantgardefinance/melon-terminal#593]
I invested ether in the fund.

After changing my mind I dis-invest in the fund. After redeem my share only chainlink in my wallet. 

I only invest Ether (weth) in the fund.

Why do I have chainlink asset now?? Why is my balance so small. Why do I not get the ether I invest in the fund??

**Comment by fubhy** [comment]
Hi.

After investing into a fund, your investment becomes part of the fund's holdings. In return, you get a fraction of the fund's shares relative to the value of your investment. When you redeem from a fund you get an equal distribution of all of the funds holdings relative to your shares.

E.g. if the fund has LINK and MLN and you invest WETH then the fund will have LINK, MLN and WETH. Redeeming will then give you an equal distribution of LINK, MLN and WETH. There is no way to just take a certain asset out of the fund as this would greatly interfere with the balances in the fund and could potentially be abused. In fact, in the upcoming version we are actually also limiting the available investment assets so that you'll only be able to invest into the fund using the denomination asset.

There is an open feature request (which we are likely going to include in our next release) to automatically swap all the redeemed tokens into a selected currency on redemption. This would be a two step process where the investor would first redeem then shares and is then offered the ability to swap them to a single token.

The feature request for that is here: https://melon.canny.io/feature-requests/p/being-able-to-convert-redemption-slice-into-one-asset

**Comment by Category55** [comment]
Redeeming will then give you an equal distribution of LINK, MLN and WETH. There is no way to just take a certain asset out of the fund as this would greatly interfere with the balances in the fund and could potentially be abused

I did not get an equal distribution of share. I invested $50 worth of weth into the fund. I recieved $38 (5.23 LINK) chainlink and $8 weth.  That is not equal. 

Just a side note: As a user of the melon protocol just had bad experience with gas fees.  I actually knew about Melon when it was $9 on the exchange and have good experience with.

**Comment by fubhy** [comment]
The distribution will he equal to the fund's current distribution of assets. So if the fund has more LINK than WETH you'll also get more LINK than WETH. Note that this distribution is relative to the denomination of these funds (WETH).

**Comment by fubhy** [comment]
And yes, the gas fees (of the entire network) are currently ridiculously high, hence why we are focusing on gas optimization and other research to reduce the gas cost for the next release.

**Comment by Category55** [comment]
They are so ridiculous they should not be the elephant in the room. Melon is a protocol characterized by high fees that wishes to "LOWER BARRIERS TO ENTRY IN ASSET MANAGEMENT"

High fees can also be characterized as HIGH BARRIERS. 

Anyways I exit the protocol for now, thank you for taking the time to explain to me. Im from South Africa, I dont have a smartphone Im just regular guy with one pair of shoes, I sell food on the streets. I have no business being on melon protocol but I did in 1 month from know nothing to investing in the fund. You guys must be very proud of yourself, you doing something right.

**Comment by fubhy** [comment]
Yes, the fees are problematic currently and we are of that. Solving this is the #1 focus of our work currently. Make sure to subscribe to https://twitter.com/melonprotocol to not miss the updates for our next release including improvements for the gas cost.
