### ISSUE TITLE
allwyn.melon.fund

### ISSUE THREAD

**Issue by AllwynBitcoinBay** [avantgardefinance/melon-terminal#604]
My fund is showimg -98% 
I have a balance of 3,651.2503 RLC in there
I thinksomehow your oracle is not showing the price for RLC and hence maybe the miscalculation
I am concerned what is the explanation to the  issue at hand?

**Comment by iherger** [comment]
Thanks for reporting this.

There was indeed no valid price for RLC when the price update was run, and therefore the RLC in your portfolio were not used to calculate the share price.

We will look into it.

**Comment by AllwynBitcoinBay** [comment]
This has caused some serious issues in the unit price value for exit and entry into the fund as well as display of performence percentages and actual values.
One is not sure what will be the effect on entry value and exit value into and out of a fund
It would be good to have a timeline for solving this issue, with correct reflections of all of the aformentioned factors.

**Comment by iherger** [comment]
It's indeed true that the performance percentages and the shares prices have been reported wrongly. This is purely in the frontend, though, and we will look into ways to improve this (i.e. we need to think about how to display performance for the cases that one or more asset prices are invalid).

Regarding investment and redemption: they are both safe on the protocol level! 

In particular: 
- investing is not possible if one of the asset prices is invalid. That means that nobody will be able to take advantage of the situation.
- redemption is always possible, because redemption pays out a slice of all the underlying assets.
