### ISSUE TITLE
Error in transaction "Cancel investment request"

### ISSUE THREAD

**Issue by CyberKingDavid** [avantgardefinance/melon-terminal#643]
Hi Guys!

The capital you want to invest is stuck. It is not possible to pay or cancel.

Can you help to me?

Regards, 
CKD

**Comment by iherger** [comment]
When you send an investment request, it is automatically executed after the next price update (once every 24 hours). I assume that your investment request has not been automatically executed because the share price has moved too much.

Cancelling your investment request is possible 24 hours after sending the investment request.
