### ISSUE TITLE
How can an investor redeem shares from fund with locked assets in trading contract?

### ISSUE THREAD

**Issue by WarrenBucket** [avantgardefinance/melon-terminal#654]
Hi,

 is it possible to somehow redeem shares from fund that has assets in trading contract?

If not, how long could the assets be in trading contract?

In a simple English, I wonder if there is any way that investor can withdraw her investment in some reasonable time or if she is left to the fate of the portfolio manager?

**Comment by iherger** [comment]
In the currently release, assets shouldn't really be stuck in the trading contract. 

Which fund is this about? Then we can have a look to see what has happened and how we can solve it.

**Comment by WarrenBucket** [comment]
The issue is only with **Qival fund I**.

**Comment by iherger** [comment]
The best way would be for the fund manager to call a function to transfer the assets into the vault contract. Alternatively, the manager can also buy any amount of UNI tokens using Kyber (not Uniswap), and the assets will end up in the vault contract automatically. 

Like this, you will be receiving your share of the tokens that are currently locked in the trading contract.

Since the fund has an investor whitelist, you might know the manager. Is there a way for you to contact the manager? We are happy to work with the fund manager to resolve this.

**Comment by WarrenBucket** [comment]
Unfortunately I don't know the fund manager.

When I invested, the fund didn't KYC whitelist yet...

**Comment by iherger** [comment]
We might know the fund manager, and we are trying to get in contact with them. I'll let you know if we succeed.

If it's urgent, there is a way to redeem anyway, and you will get your share of all the tokens, except for the tokens that are stuck in the trading contract. Let me know if you want to go this route.

**Comment by WarrenBucket** [comment]
Hi Ivan,

 I am able to wait for a while, but if there will be no response from portfolio manager, then I would go that way...

**Comment by WarrenBucket** [comment]
Hi,

 could you please contact me privatly with next steps about partial redemption?

Thank you for your help

**Comment by iherger** [comment]
This should now be possible for the fund you were looking at earlier.

**Comment by WarrenBucket** [comment]
This partial issue with smart contract is sorted now! Thank you.
